#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    find_results=()

    find_results=()
    find_results=($(find ~/programming -mindepth 1 -maxdepth 2 -type d))
    find_results+=($(find ~/.dotfiles -mindepth 0 -maxdepth 0 -type d))
    find_results+=($(find ~/Tobi_Nextcloud/University/Bachelorarbeit/ -mindepth 0 -maxdepth 1 -type d))
    #find_results+=($(find ~/OneDrive/Universität/5.Semester/ -mindepth 0 -maxdepth 0 -type d))
    
    selected=$(echo "${find_results[@]}" | tr ' ' '\n' | fzf)
fi


if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name

