#include QMK_KEYBOARD_H
#if __has_include("config.h")
#include "config.h"
#endif

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x6_3(
        LSFT(KC_1), KC_Q, KC_W, KC_F, KC_P, KC_B, KC_M, KC_L, KC_U, KC_Z,
        LSFT(KC_GT), LSFT(KC_NUBS), KC_PPLS, LGUI_T(KC_A), LALT_T(KC_R),
        LSFT_T(KC_S), LCTL_T(KC_T), KC_G, KC_M, RCTL_T(KC_N), RSFT_T(KC_E),
        LALT_T(KC_I), LGUI_T(KC_O), KC_SLSH, RALT(KC_Q), KC_Y, KC_X, KC_C, KC_D,
        KC_V, KC_K, KC_H, KC_COMM, KC_DOT, LSFT(KC_COMM), LSFT(KC_MINS), KC_ESC,
        KC_TAB, LT(2, KC_SPC), LT(1, KC_ENT), KC_BSPC, KC_DEL),

    [1] = LAYOUT_split_3x6_3(KC_TRNS, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7,
                             KC_8, KC_9, KC_0, KC_TRNS, KC_TRNS, KC_NUBS,
                             LSFT(KC_2), LSFT(KC_7), RALT(KC_MINS), LSFT(KC_5),
                             LSFT(KC_6), RALT(KC_E), LSFT(KC_4), KC_NO, KC_NO,
                             KC_TRNS, KC_TRNS, RALT(KC_RBRC), LSFT(KC_5),
                             LSFT(KC_BSLS), RALT(KC_NUBS), KC_EQL, KC_NO, KC_NO,
                             KC_TRNS, KC_TRNS, LSFT(KC_MINS), KC_NO, KC_TRNS,
                             KC_TRNS, MO(3), KC_TRNS, KC_TRNS, KC_TRNS),

    [2] = LAYOUT_split_3x6_3(
        KC_TRNS, KC_NUBS, LSFT(KC_8), RALT(KC_7), RALT(KC_8), KC_NO, KC_PGUP,
        RALT(KC_9), RALT(KC_0), LSFT(KC_9), LSFT(KC_NUBS), KC_TRNS, KC_TRNS,
        KC_QUOT, LSFT(KC_RBRC), KC_GRV, LSFT(KC_7), LSFT(KC_5), KC_LEFT,
        KC_DOWN, KC_UP, KC_RGHT, KC_SCLN, KC_TRNS, KC_TRNS, KC_NO, KC_NO,
        KC_MINS, LSFT(KC_0), KC_NO, KC_PGDN, KC_LBRC, KC_TRNS, KC_TRNS,
        LSFT(KC_MINS), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, MO(3), KC_TRNS,
        KC_TRNS),

    [3] = LAYOUT_split_3x6_3(
        KC_NO, KC_MUTE, KC_VOLD, KC_VOLU, KC_NO, KC_HOME, MS_WHLU, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MNXT, KC_MPLY, KC_NO, KC_PSCR,
        KC_NO, KC_END, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_MPRV, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, MS_WHLD, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, LT(2, KC_SPC), LT(1, KC_ENT),
        KC_TRNS, KC_TRNS)};

uint16_t get_tapping_term(uint16_t keycode, keyrecord_t *record) {
  switch (keycode) {
  default:
    return TAPPING_TERM;
  }
}
#ifdef OTHER_KEYMAP_C
#include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C
